Understanding workflow error handling
=====================================
:compat-mode!:
// Metadata:
:description: Understanding workflow error handling
:keywords: kogito, workflow, serverless, error

This guide explains how to handle errors that might occur while executing workflow states. Although a non-desirable situation, Workflow states might fail as part of their interaction with external systems. For these situations, the Serverless Workflow specification provides an link:{spec_doc_url}#workflow-error-handling[error handling] mechanism, allowing users to deal with these rainy day circumstances.

An error is an exceptional occurrence that alters the regular Workflow execution sequence. When an error occurs, rather than transitioning to the state that would have been executed in case of successful execution, the workflow, if configured to do so, jumps instead to an alternative state, potentially capable of dealing with it. Note that error definition is always optional. If no error handling is defined, the Workflow execution will be aborted when something goes wrong. If you are a software developer, you can think of Workflow error handling as a `try-catch` or a `goto` construct.

== Error definition

An link:{spec_doc_url}#error-definition[Error definition] in Serverless Workflow is composed of a name and a code. The name is a natural language description of the error, for example: 'wrong parameter', while the code is a vendor-specific parameter that helps the implementation to identify the error. In the case of Kogito, the code is mandatory and consists of the fully qualified Java class name of an link:https://docs.oracle.com/javase/tutorial/essential/exceptions/index.html[Exception type] that the state might throw.

The steps used by Kogito to determine if an exception should be handled by an error definition are:

* It checks if the type of the Java Exception being thrown is an instance (which includes any descendant) of the Java Exception specified in `code` property of the error definition. 
* If this not the case, it recursively applies the same check to the root cause of the original Java Exception, till the exception chain is exhausted. 

== Error handling example 

The workflow in the link:{kogito_sw_examples_url}/serverless-workflow-error-quarkus[Serverless Workflow Error Quarkus] example illustrates the error handling feature, as shown in the image below. 

image::core/error_handling.png []

This workflow accepts an integer number as the input model. When the workflow starts, it invokes the `isEven` service passing that number as a parameter. This link:{kogito_sw_examples_url}serverless-workflow-error-quarkus/src/main/java/org/kie/kogito/examples/EvenService.java[Java service] throws an `IllegalArgumentException` exception if the number is odd. This means that if the number is even, the flow will transition to the `even` state, but if the number is odd, the flow will move to the `odd` state, resulting in different model output. The link:{spec_doc_url}#inject-state[Inject] state purpose is to populate the model with some specific JSON payload, therefore the `even` state sets the `message` property to __even__ and the `odd` state consequently sets it to __odd__. The `finish` state dumps the model content to the console, so the user can verify the expected message has been set. 

This functionality is achieved by:

* Defining a function that invokes the `isEven` method of `org.kie.kogito.examples.EvenService` class. This function uses link:{spec_doc_url}#defining-custom-function-types[custom type] to enable the workflow to invoke java methods.
+
[source, json]
----
{
    "name": "isEven",
    "type": "custom",
    "operation": "service:java:org.kie.kogito.examples.EvenService::isEven"
}
----
* Adding an error definition that handles any runtime exception at the beginning of the link:{kogito_sw_examples_url}/serverless-workflow-error-quarkus/src/main/resources/error.sw.json[workflow]. 
+
[source, json]
----
"errors": [
    {
      "name": "odd number",
      "code": "java.lang.RuntimeException"
     }
  ]
----
* Referring to this error definition in the `checkEven` state. If this error occurs, the workflow should transition to the `odd` state rather than the regular transition to the `even` state. Since `IllegalArgumentException` is a child of `RuntimeException`, it will be handled by the `errorRef` if thrown by the `isEven` function.
+
[source,json]
----
{
      "name": "checkEven",
      "type": "operation",
      "actions": [
        {
          "name": "checkEvenAction",
          "functionRef": {
            "refName": "isEven",
            "arguments": {
              "number": "$.number"
            }
          }
        }
      ],
      "transition": "even",
      "onErrors": [
        {
          "errorRef": "odd number",
          "transition": "odd"
        }
      ]
    }
----

== Additional resources

* xref:getting-started/create-your-first-workflow-service.adoc[Create your first Workflow Service].

include::../../pages/_common-content/report-issue.adoc[]


